#!/usr/bin/env python3
"""
Render a glossy 3D-feeling heart at 200×200:
- iconic emoji parametric curve, supersampled and resampled (clean shape)
- radial color gradient inside (bright crimson upper-left → deep ruby lower-right)
- specular highlight (soft white bloom on the upper-left lobe)
- soft outer glow (subtle red halo bleeding past the silhouette)

Output as LVGL 9 ARGB8888 premultiplied alpha. Memory layout: B, G, R, A.

Output: src/assets/heart.c
"""
import math
from pathlib import Path

from PIL import Image, ImageDraw, ImageFilter

W, H = 200, 200
SS = 4
OUT = Path("src/assets/heart.c")

# colors (RGB)
BRIGHT  = (255, 100, 130)   # upper-left, light-struck
MID     = (228,  38,  56)   # body crimson
DEEP    = (148,  16,  36)   # lower-right shadow
SPEC    = (255, 230, 235)   # specular highlight (almost white-pink)
GLOW    = (220,  30,  50)   # outer glow tint

LIGHT_POS = (0.30, 0.30)    # 0..1 inside image; upper-left lobe area


def heart_polygon(w, h, n=512):
    pts = []
    for i in range(n):
        t = i * 2 * math.pi / n
        x = 16 * (math.sin(t) ** 3)
        y = 13 * math.cos(t) - 5 * math.cos(2 * t) - 2 * math.cos(3 * t) - math.cos(4 * t)
        pts.append((x, -y))
    xs, ys = zip(*pts)
    minx, maxx = min(xs), max(xs)
    miny, maxy = min(ys), max(ys)
    bw, bh = maxx - minx, maxy - miny
    margin = 0.86       # leave room around heart for the outer glow
    scale = min(w / bw, h / bh) * margin
    cx, cy = (minx + maxx) / 2, (miny + maxy) / 2
    return [(int((px - cx) * scale + w / 2),
             int((py - cy) * scale + h / 2)) for px, py in pts]


def lerp(a, b, t):
    return tuple(int(a[i] + (b[i] - a[i]) * t) for i in range(3))


def main():
    big_w, big_h = W * SS, H * SS

    # ── 1) silhouette alpha mask ──
    mask_big = Image.new("L", (big_w, big_h), 0)
    ImageDraw.Draw(mask_big).polygon(heart_polygon(big_w, big_h), fill=255)
    mask = mask_big.resize((W, H), Image.LANCZOS)

    # ── 2) color body with radial gradient + specular ──
    body = Image.new("RGB", (W, H), DEEP)
    lx, ly = LIGHT_POS[0] * W, LIGHT_POS[1] * H
    max_d = math.hypot(W * 0.9, H * 0.9)
    spec_r = 0.16 * W                 # specular spot radius

    px = body.load()
    for y in range(H):
        for x in range(W):
            d = math.hypot(x - lx, y - ly)
            t = min(1.0, d / max_d * 1.3)       # 0 at light, 1 at far corner
            # ease-in for richer falloff
            te = t * t
            color = lerp(BRIGHT, DEEP, te)
            # blend toward MID in the middle band for depth
            tm = 1.0 - abs(0.5 - te) * 2
            color = lerp(color, MID, 0.35 * tm)
            # specular halo near light source
            if d < spec_r * 2:
                spec_t = max(0.0, 1.0 - d / (spec_r * 2)) ** 2
                color = lerp(color, SPEC, 0.55 * spec_t)
            px[x, y] = color

    # ── 3) outer glow: blur silhouette outward, tint, layer behind ──
    glow_alpha = mask.filter(ImageFilter.GaussianBlur(radius=6))
    # subtract the original mask region so glow only shows OUTSIDE the heart
    glow_only = Image.eval(glow_alpha, lambda v: int(v * 0.45))
    glow_rgb  = Image.new("RGB", (W, H), GLOW)

    # ── 4) composite RGBA ──
    out = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    # paint glow first (lower opacity, full-image)
    out.paste(glow_rgb, mask=glow_only)
    # paint heart body on top, masked to its silhouette
    out.paste(body, mask=mask)
    # make final alpha the union: glow_only OR mask
    final_alpha = Image.eval(mask, lambda v: v)
    # take max of mask and glow_only as alpha plane
    fa = final_alpha.load(); ga = glow_only.load()
    for y in range(H):
        for x in range(W):
            fa[x, y] = max(fa[x, y], ga[x, y])
    out.putalpha(final_alpha)

    out.save("/tmp/heart_preview.png")

    # ── 5) serialize ARGB8888 premultiplied ──
    pix = out.tobytes()
    buf = bytearray(len(pix))
    for i in range(0, len(pix), 4):
        r, g, b, a = pix[i], pix[i + 1], pix[i + 2], pix[i + 3]
        pr = (r * a) // 255
        pg = (g * a) // 255
        pb = (b * a) // 255
        buf[i] = pb; buf[i + 1] = pg; buf[i + 2] = pr; buf[i + 3] = a

    lines = [
        "// Auto-generated by scripts/gen_heart_asset.py",
        f"// {W}×{H} glossy crimson heart, ARGB8888 premultiplied.",
        "// Radial gradient (bright upper-left → deep lower-right) + specular + outer glow.",
        "",
        "#include <lvgl.h>",
        "",
        "#ifndef LV_ATTRIBUTE_MEM_ALIGN",
        "#define LV_ATTRIBUTE_MEM_ALIGN",
        "#endif",
        "",
        "static const LV_ATTRIBUTE_MEM_ALIGN uint8_t img_heart_data[] = {",
    ]
    for i in range(0, len(buf), 16):
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in buf[i:i + 16]) + ",")
    lines += [
        "};",
        "",
        "const lv_image_dsc_t img_heart = {",
        "    .header = {",
        "        .magic = LV_IMAGE_HEADER_MAGIC,",
        "        .cf = LV_COLOR_FORMAT_ARGB8888,",
        "        .flags = LV_IMAGE_FLAGS_PREMULTIPLIED,",
        f"        .w = {W},",
        f"        .h = {H},",
        f"        .stride = {W * 4},",
        "        .reserved_2 = 0,",
        "    },",
        "    .data_size = sizeof(img_heart_data),",
        "    .data = img_heart_data,",
        "    .reserved = NULL,",
        "};",
        "",
    ]
    OUT.write_text("\n".join(lines))
    print(f"{OUT}: {W}×{H}, {OUT.stat().st_size} bytes C")
    print(f"preview at /tmp/heart_preview.png")


if __name__ == "__main__":
    main()
